#!/usr/bin/env python3

# external
import sys, os
from PyQt4.QtGui import QApplication
# internal
from cr import *

# main
if __name__ == "__main__":
  sys.path.append('%s/cr/drivers/' % os.path.dirname(os.path.realpath(__file__)))
  qapp = QApplication(sys.argv)
  settings = Settings(qapp)
  mainWindow = MainWindow(settings)
  mainWindow.show()
  qapp.exec_()

